export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';

export const CREATE_NEW_BOOK = 'CREATE_NEW_BOOK';
export const ADD_NEW_BOOK = 'ADD_NEW_BOOK';

export const JOIN_ITEMS = 'JOIN_ITEMS';
